- name : Configure Docker on EC2 Instances
  hosts : all
  become: true
    #become_user: root
    #connection : ssh
  tasks:
    - name: Updating apt
      apt:
        update_cache: yes
      become: true

    - name: Install Docker
      apt:
        name: docker.io
        state: present
      become: true

    - name: Start Docker Service
      systemd:
        name: docker
        state: started
        enabled: yes
      become: true

    - name: Pull Docker Image
      docker_image:
        name: indu1919/finance-me-bank:v1
        source: pull
      become: true

    - name: Deploy Docker Container
      docker_container:
        name: finance-me-bank
        image: indu1919/finance-me-bank:v1
        ports:
          - "8086:8081"
        state: started
        restart_policy: always
      become: true
